name: Test workflow
run-name: Test workflow ${{ github.run_number }}

defaults:
  run:
    shell: bash

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment: 
        description: "Envrionment to deploy"
        type: environment
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the folling files:"
          tree
  test:
    runs-on: ubuntu-latest
    environment: test
    if: github.event_name == 'workflow_dispatch'
    name: Test
    needs: [build]
    steps: 
      - run: echo "Testing..."
  load-test:
    runs-on: ubuntu-latest
    environment: load-test
    if: github.event_name == 'workflow_dispatch'
    name: Load test
    needs: [build]
    steps: 
      - run: |
          echo "Testing..."
          sleep 15
  production:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    name: Production deployment
    needs: [test, load-test]
    steps: 
      - run: |
          echo "Deploying step 1..."
          sleep 5
      - run: |
          echo "Deploying step 2..."
          sleep 5
      - run: |
          echo "Deploying step 3..."
          sleep 5
      - run: |
          echo "Deploying step 4..."
          sleep 5
      - run: |
          echo "Deploying step 5..."
          sleep 5
      
